spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/emart_order
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
server:
  port: 9093
  servlet:
    context-path: /api
    
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      company-name: eureka
  client:
    registry-fetch-interval-seconds: 30
    service-url:   
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.security: INFO
ribbon:
  eureka:
    enabled: true