From java:openjdk-8

MAINTAINER wenhongpeng

ADD ./eureka_server-0.0.1-SNAPSHOT.jar /home/eureka_server-0.0.1-SNAPSHOT.jar

EXPOSE 8080
ENTRYPOINT ["java","-jar","/home/eureka_server-0.0.1-SNAPSHOT.jar"]