version: '3'
services:
  web:
    build: .
    ports:
      - "9090:9090"
    links:
      - mysql:mysql
  mysql:
    container_name: mysql
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_DATABASE: emart_user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '123456'
    ports:
      - "3306:3306"
    restart: always
  