spring:
  application:
    name: zuul-service
server:
  port: 9000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  host:    connect-timeout-millis: 60000
    socket-timeout-millis: 60000   
  ribbon:    eager-load:      enabled: true
  routes:
    auth:
      path: /user/**
      serviceId: user-service
      strip-prefix: false
    item:
      path: /api/item/**
      serviceId: item-service
      strip-prefix: false
    cart:
      path: /api/cart/**
      serviceId: cart-service
      strip-prefix: false
    order:
      path: /api/order/**
      serviceId: order-service
      strip-prefix: false
data-filter:
  auth-path: #validate token, will trigger JwtAuthPreFilter
    - /api/**
  user-login-path: #add token, LoginAddJwtPostFilter
    - /user/login/**
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
 
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

    
     